# Matrizen und Vektoren

In [5]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=np.array([[1,2,3,4],[10,11,12,13]])

V1=np.array([10,20])
V2=np.array([11,22])
print("A\n",A)
print("B\n",B)

A
 [[1 2]
 [3 4]]
B
 [[5 6]
 [7 8]]


In [6]:
#Shapes
print("Matrix C\n",C)
print("Dimensionen von C:",C.shape)
print("Anzahl der Zeilen:",C.shape[0])#Zeilen
print("Anzahl der Spalten:", C.shape[1])#Spalten
print()
print("Vektor V1",V1)
print("Zeilen von V1:",V1.shape)

Matrix C
 [[ 1  2  3  4]
 [10 11 12 13]]
Dimensionen von C: (2, 4)
Anzahl der Zeilen: 2
Anzahl der Spalten: 4

Vektor V1 [10 20]
Zeilen von V1: (2,)


# Rechenoperationen mit Arrays bei verschiedenen Dimensionen

In [7]:
#Addition von Vektoren oder Matrizen mit gleicher Dimension
print("V1",V1,"  V2",V2,"  V1 + V2 =",V1+V2)
print()
print("A + B=\n",A+B)
print()
print("C",C)
print("A",A)
# print(A+C)
#Bei der Addition von mehrdimensionalen Gebilden, 
#werden die Werte an entsprechenden Stellen addiert.

V1 [10 20]   V2 [11 22]   V1 + V2 = [21 42]

A + B=
 [[ 6  8]
 [10 12]]

C [[ 1  2  3  4]
 [10 11 12 13]]
A [[1 2]
 [3 4]]


In [8]:
#Addition von Matrizen und Zahlen
print(A+1)

[[2 3]
 [4 5]]


In [9]:
#Multiplikation
print("5*V1 = ",5*V1,"\n")
print("A = \n",A,"\n")
print("5*A = \n",5*A)

5*V1 =  [ 50 100] 

A = 
 [[1 2]
 [3 4]] 

5*A = 
 [[ 5 10]
 [15 20]]


In [10]:
#Hier noch einmal die Ausgabe von A und V1
print("A",A[0],"\tV1[",V1[0])
print(" ",A[1],"\t   ",V1[1],"]")

A [1 2] 	V1[ 10
  [3 4] 	    20 ]


In [11]:
#Multiplikation von Matrix und Vektor: meistens ungewollt
A*V1

array([[10, 40],
       [30, 80]])

In [12]:
A*np.array([[-1,-2],[-3,-4]])#Beispiel für  * - Multiplikation 

array([[ -1,  -4],
       [ -9, -16]])

In [13]:
#Skalar-Multiplikation liefert einfache Werte
print("simple Multiplikation",V1 *V1)
print("Skalarmultiplikation",V1 @ V1)

#Skalarmultiplikation:V1[0]*V2[0] + V1[1]*V2[1]

simple Multiplikation [100 400]
Skalarmultiplikation 500


In [14]:
#Skalar-Multiplikation liefert einfache Werte
V1=np.array([1,2]); V2=np.array([3,4])
print("simple Multiplikation",V1 *V2)
print("Skalarmultiplikation",V1 @ V2)
#Skalarmultiplikation:V1[0]*V2[0] + V1[1]*V2[1]

simple Multiplikation [3 8]
Skalarmultiplikation 11


# Wozu kann man den Operator @ benutzen ? (bei Vektoren)

### Winkel prüfen

In [15]:
#Mit Skalarmultiplikation kann man prüfen, ob 2 Vektoren senkrecht aufeinander stehen
np.array([1,1])@np.array([1,-1])
#Bitte in ein Koordinatensystem einzeichnen und den rechten Winkel überprüfen

0

### Länge berechnen

In [16]:
#Skalarmultiplikation liefert die Länge eines Vektors
V3=np.array([3,4])
print("Länge von [3,4] =",np.sqrt( V3@V3 ))

Länge von [3,4] = 5.0


### Drehungen von geometrischen Vektoren

In [17]:
#Matrixmultiplikation bewirkt bei Vektoren manchmal eine Drehung
Dreh90=np.array([[0,-1],[1,0]])
V3=np.array([0,1])
print(V3, "gedreht um 90 Grad, ergibt", Dreh90 @V3)

[0 1] gedreht um 90 Grad, ergibt [-1  0]


In [18]:
#Matrixmultiplikation bewirkt bei Vektoren manchmal eine Drehung
Dreh30=np.array([[np.sqrt(3)/2,-0.5],[0.5,np.sqrt(3)/2]])
V3=np.array([0,1])
print(V3, "gedreht um 30 Grad, ergibt", Dreh30 @ V3)

[0 1] gedreht um 30 Grad, ergibt [-0.5        0.8660254]


# Weitere Rechenoperationen mit Matrizen

### Multiplikation von 2 Matrizen

In [19]:
# Matrizen kann man auch mit anderen Matrizen multiplizieren
print (A,"\nmultipliziert mit \n",B, "\nist\n",A@B)
#statt A@B kann man auch A.dot(B)schreiben
print("oder\n",A.dot(B))

[[1 2]
 [3 4]] 
multipliziert mit 
 [[5 6]
 [7 8]] 
ist
 [[19 22]
 [43 50]]
oder
 [[19 22]
 [43 50]]


In [20]:
# Bei Matrizen gibt es ein "neutrales Element"
E=np.array([[1,0],[0,1]])
print("A\n",A)
print("A @ E \n",A@E)

A
 [[1 2]
 [3 4]]
A @ E 
 [[1 2]
 [3 4]]


### Inverse Matrix

In [21]:
#Manche Matrizen kann man "umkehren". 
print("A",A)
print("Inverses von A")
A_inv=np.linalg.inv(A)
print(A_inv)
print("\nProdukt der Matrix A mit ihrer inversen Matrix")
print(np.round(A@A_inv))
print ("A@A_inv ergibt die Einheitsmatrix :",np.allclose(A@A_inv , E))
# Wenn man das Resultat von A@A_inv == E ermittelt, ist es nicht das gewünschte, 
# denn es berechnet eine 2x2 Matrix aus Wahrheitwerten.
# Deswegen vergleicht man Matrizen über die Funktion allclose

A [[1 2]
 [3 4]]
Inverses von A
[[-2.   1. ]
 [ 1.5 -0.5]]

Produkt der Matrix A mit ihrer inversen Matrix
[[1. 0.]
 [0. 1.]]
A@A_inv ergibt die Einheitsmatrix : True


### Transponierte Matrix

In [22]:
#Alle Matrizen kann man transponieren(an der Diagonalen spiegeln)
print("Original")
print(A)
print("transponiert")
print(A.T)
print("transponiert, Variante")
print(A.transpose())

Original
[[1 2]
 [3 4]]
transponiert
[[1 3]
 [2 4]]
transponiert, Variante
[[1 3]
 [2 4]]


In [23]:
#Alle Matrizen kann man transponieren, auch die unsymmetrischen
print("Original")
print(C)
print("\ntransponiert")
print(C.T)

Original
[[ 1  2  3  4]
 [10 11 12 13]]

transponiert
[[ 1 10]
 [ 2 11]
 [ 3 12]
 [ 4 13]]


In [24]:
#Die Gestalt der Matrizen abfragen
print("Die Zeilen und Spalten von C",C.shape)
print("Die Zeilen und Spalten von C_transponiert",C.T.shape)

Die Zeilen und Spalten von C (2, 4)
Die Zeilen und Spalten von C_transponiert (4, 2)


# Rechenoperationen, die sich nur auf Zeilen oder Spalten beziehen

In [25]:
#Rechenoperationen bei Matrizen
#Bitte sehr gründlich nachvollziehen !!!
summe1=np.sum(A)
Summe2=np.sum(A,axis=0)
Summe3=np.sum(A,axis=1)
print("A\n",A)
print("Summe aller Komponenten",summe1,", Spaltensumme",Summe2,",Zeilensumme",Summe3)
#Achtung: das ist nicht intuitiv: 
#wenn axis=0 geschrieben wird, dann handelt es sich um die Summe in Spalten

A
 [[1 2]
 [3 4]]
Summe aller Komponenten 10 , Spaltensumme [4 6] ,Zeilensumme [3 7]


In [26]:
#Bitte dasselbe noch einmal testen, mit np.prod

In [27]:
#Rechenoperationen bei dreidimensionalen Matrizen
#Bitte sehr gründlich nachvollziehen !!!
C222=C.reshape(2,2,2)
summe1=np.sum(C222)
Summe2=np.sum(C222,axis=0)
Summe3=np.sum(C222,axis=1)
Summe4=np.sum(C222,axis=2)
print("C222")
print("[",C222[0,0], "  ",C222[0,1],"]")
print("[",C222[1,0], C222[1,1],"]")
print("Summe aller Komponenten",summe1)
print("Summe, bei der die Zeilen verschwinden")
print(Summe2)
print("Summe , bei der innerhalb einer Zeile entsprechende Spaltenkomponenten verschwinden")
print(Summe3)
print("Summe, bei der die innerste Achse verschwindet")
print(Summe4)

C222
[ [1 2]    [3 4] ]
[ [10 11] [12 13] ]
Summe aller Komponenten 56
Summe, bei der die Zeilen verschwinden
[[11 13]
 [15 17]]
Summe , bei der innerhalb einer Zeile entsprechende Spaltenkomponenten verschwinden
[[ 4  6]
 [22 24]]
Summe, bei der die innerste Achse verschwindet
[[ 3  7]
 [21 25]]
