# Ausgangssituation

In [1]:
import numpy as np
np.random.seed(42)
b1=np.random.randint(1,10,3 )*2
print(b1)
b2=np.random.randint(1,10,3) *2
print("b1",b1,"b2",b2)
A=np.c_[b1,b2].T
print("zwischen vektor\n",np.c_[b1,b2])
A[0,0]= 0
A[1,1]= 0
print("Die Ausgangsmatrix")
print(A)

[14  8 16]
b1 [14  8 16] b2 [10 14  6]
zwischen vektor
 [[14 10]
 [ 8 14]
 [16  6]]
Die Ausgangsmatrix
[[ 0  8 16]
 [10  0  6]]


In [2]:
import numpy as np
np.random.seed(42)
a=np.random.randint(0,10,10) *2
a[5] = a[6] = 0
print("Ein Vektor zum Beginn",a)


Ein Vektor zum Beginn [12  6 14  8 12  0  0 12 14  8]


# Elemente auswählen, die an bestimmten Indizes stehen

In [3]:
#Es gibt 3 Möglichkeiten, auf Elemente zuzugreifen, wenn man deren Positionen kennt
print("3.Element:    ", a[2])
print("Elemente mit Hilfe von Slicing bestimmen (Positionen 0 bis 2):\t",a[1:3])

print("Elemente mit Hilfe von Index-Arrays( Indizes 1,2):\t",
      a[ [1,2]])
print("Elemente mit Hilfe von Index-Arrays( Indizes 0,2,6):\t",
      a[ [0,2,6]])

3.Element:     14
Elemente mit Hilfe von Slicing bestimmen (Positionen 0 bis 2):	 [ 6 14]
Elemente mit Hilfe von Index-Arrays( Indizes 1,2):	 [ 6 14]
Elemente mit Hilfe von Index-Arrays( Indizes 0,2,6):	 [12 14  0]


# Elemente finden, wo der Wert eine bestimmte Bedingung erfüllt

### np.where

In [4]:
#Indizes zurückgeben, wenn der Wert eine bestimmte Bedingung erfüllt

print("Original",a)
i1=np.where(a <=8)
print("np.where liefert die Indizes , wo der Inhalt <= 8\n",i1,"\n")

Original [12  6 14  8 12  0  0 12 14  8]
np.where liefert die Indizes , wo der Inhalt <= 8
 (array([1, 3, 5, 6, 9], dtype=int64),) 



In [5]:
#Indizes benutzen , um an die Werte zu kommen
print("Die Bestandteile von a, die  <= 8 sind",      a[i1])

Die Bestandteile von a, die  <= 8 sind [6 8 0 0 8]


In [6]:
# identische Wirkung: 
print("Mittelwert von a",a.mean())
print("Die Bestandteile von a, die größer als der Mittelwert sind",   a[ np.where(a>a.mean()) ])
print()
print("Aus a wird alles, was nicht mit der Bedingung übereinstimmt, entfernt.")

Mittelwert von a 8.6
Die Bestandteile von a, die größer als der Mittelwert sind [12 14 12 12 14]

Aus a wird alles, was nicht mit der Bedingung übereinstimmt, entfernt.


### np.nonzero, np.flatnonzero

In [7]:
print("nonzero wird eigentlich auf arrays angewandt und unterdrückt die Nullen")
print("Ausgangsarray für nonzero",a)

nonzero wird eigentlich auf arrays angewandt und unterdrückt die Nullen
Ausgangsarray für nonzero [12  6 14  8 12  0  0 12 14  8]


In [8]:
print("original",a)
print("nonzero(a)=",np.nonzero(a),".\n\t    Dies sind Indizes !")
print()

original [12  6 14  8 12  0  0 12 14  8]
nonzero(a)= (array([0, 1, 2, 3, 4, 7, 8, 9], dtype=int64),) .
	    Dies sind Indizes !



In [9]:
print("Original",a)
i2=np.nonzero( a >10)
print("np.nonzero kann auch mit Wahrheitswerten gebraucht werden, nämlich da,wo der Boolsche Ausdruck =True")
print("'Die Indizes, wo a >10' =",i2)
#Die Indizes werden überall dort zurückgegeben, 
#wo das Boolean in der Klammer != False ist, deswegen heißt die Funktion "nonzero"
#Mit den Indizes alle Bestandtteile, die die Bedingung erfüllen herausfiltern.
print("Die Zahlen aus dem Original-Array, die größer als 10 sind",a[i2])
# oder:
#print("Die Zahlen aus dem Original-Array, die größer als 10 sind",a[np.nonzero( a >3)])

Original [12  6 14  8 12  0  0 12 14  8]
np.nonzero kann auch mit Wahrheitswerten gebraucht werden, nämlich da,wo der Boolsche Ausdruck =True
'Die Indizes, wo a >10' = (array([0, 2, 4, 7, 8], dtype=int64),)
Die Zahlen aus dem Original-Array, die größer als 10 sind [12 14 12 12 14]


In [10]:
b=np.array([[11,0,22],[0,33,44]]);print("mehrdimensional: b Original\n",b)
i3=np.flatnonzero(b)
print("flatnonzero lässt die Nullen weg und macht aus dem Ganzen ein eindimensionales Array")
print()
print("Dies sind die Indizes des flachen Arrays, wo keine Nullen stehen",i3)
print("Ergebnis für b nach Flattening", b.flatten())
print("Ergebnis für b nach Flattening und Zero-Entfernung", b.flatten()[i3])

mehrdimensional: b Original
 [[11  0 22]
 [ 0 33 44]]
flatnonzero lässt die Nullen weg und macht aus dem Ganzen ein eindimensionales Array

Dies sind die Indizes des flachen Arrays, wo keine Nullen stehen [0 2 4 5]
Ergebnis für b nach Flattening [11  0 22  0 33 44]
Ergebnis für b nach Flattening und Zero-Entfernung [11 22 33 44]


# Mehrdimensionales np.where 

### Achtung: hier müssen die Indizes kompliziert zusammengebaut werden.

In [11]:
#A=np.array([[1,2,3],[4,5,1]])
print("A")
print(A)
#print()
print("Indizes der Elemente, die größer als 2 sind",np.where(A > 2))
print()
#hier werden 2 Arrays zurückgegeben, sie enthalten jeweils die Koordinaten für die erste und zweite Achse
#Wenn man die Werte aus A herausholen will, muss je ein Wert aus dem ersten und dem 2. Index-Array kombiniert werden.
#z.B
print("Die Elemente, die in A = > 2 sind:",A[0,2],",",A[1,0],",",A[1,1])
print("Die Elemente, die in A = > 2 sind:",A[np.where(A>2)])

A
[[ 0  8 16]
 [10  0  6]]
Indizes der Elemente, die größer als 2 sind (array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2], dtype=int64))

Die Elemente, die in A = > 2 sind: 16 , 10 , 0
Die Elemente, die in A = > 2 sind: [ 8 16 10  6]


# Indizes, die von bestimmten Funktionen geliefert werden, z.B. min, max

In [12]:
print("Steht vor einer Funktion die Vorsilbe arg, liefert sie ebenfalls Indizes")
i5=np.argmin(a)
print("Original",a)
print("Minimaler Wert im Array:",np.min(a))
print("np.argmin liefert den frühesten Index des Minimums:",i5)
#analog np.argmax

Steht vor einer Funktion die Vorsilbe arg, liefert sie ebenfalls Indizes
Original [12  6 14  8 12  0  0 12 14  8]
Minimaler Wert im Array: 0
np.argmin liefert den frühesten Index des Minimums: 5


# Ersetzen von bestimmten Werten

In [13]:
#Wiederholung 
#Aus den Indizes eine Teilmatrix zurückgewinnen
print("Original",a)
indizes=np.where(a>3)
print("alle Elemente von a, die größer als 3 sind",a[indizes])
print("alle Elemente von a, die größer als 3 sind",a[np.where(a>3)])

Original [12  6 14  8 12  0  0 12 14  8]
alle Elemente von a, die größer als 3 sind [12  6 14  8 12 12 14  8]
alle Elemente von a, die größer als 3 sind [12  6 14  8 12 12 14  8]


### Ersetzen mit Boolean Bedingungen (np.where)

In [14]:
print("Original",a)
print("Ersetzen durch einfache Zahlenangabe")
print("alles was identisch mit 6 war, wird durch 'sechs' ersetzt, alles andere wird durch '--' ersetzt")
a1=np.where(a == 6,"sechs","---")
print(" geänderter Array",a1)
print()
a2=np.where(a == 6,111,a)
print("nur Werte, die eine bestimmte Bedingung erfüllen wurden geändert\n","andere Werte bleiben erhalten\n",a2)

Original [12  6 14  8 12  0  0 12 14  8]
Ersetzen durch einfache Zahlenangabe
alles was identisch mit 6 war, wird durch 'sechs' ersetzt, alles andere wird durch '--' ersetzt
 geänderter Array ['---' 'sechs' '---' '---' '---' '---' '---' '---' '---' '---']

nur Werte, die eine bestimmte Bedingung erfüllen wurden geändert
 andere Werte bleiben erhalten
 [ 12 111  14   8  12   0   0  12  14   8]


### Ersetzen durch Angabe von Indizes (np.put)

In [15]:
#Werte ersetzen, wenn man schon weiß, an welchen Stellen die Ersatzwerte platziert werden.
c=np.array([1,3,5,7]);
print(c)
indices=[0,2]
ersatz_werte=[-44, -55]
np.put(c, indices, ersatz_werte)
print("geändert",c)
print("!!! Achtung: die Originalwerte wurden gelöscht !")

[1 3 5 7]
geändert [-44   3 -55   7]
!!! Achtung: die Originalwerte wurden gelöscht !


### Zusätze

In [16]:

print("Original\n",A)
#where liefert ganz normale Indices
i1=np.where(A ==0)
print("Indizes , wo der Inhalt =0\t...........................",i1)
print("Inhalte von a, angesprochen von den Indizes i1....................",A[i1])
#argwhere liefert eine Matrix aus Indizes
i2=np.argwhere(A == 0)# a==0 definiert einen Array, von dem werden nur die Indizes zurückgegeben, die True sind.
print("Index-Matrix, wo die Bedingung =True\n",i2)# Hier kann man Index-Tupel entnehmen


Original
 [[ 0  8 16]
 [10  0  6]]
Indizes , wo der Inhalt =0	........................... (array([0, 1], dtype=int64), array([0, 1], dtype=int64))
Inhalte von a, angesprochen von den Indizes i1.................... [0 0]
Index-Matrix, wo die Bedingung =True
 [[0 0]
 [1 1]]


# Anwendung auf die Aufgabe

In [17]:
A

array([[ 0,  8, 16],
       [10,  0,  6]])

In [18]:
Means=A.mean(axis=0)
print("Means",Means)

Means [ 5.  4. 11.]


In [19]:
B=np.where(A==0,Means,A)
print("nach der Ersetzung")
print(B)

nach der Ersetzung
[[ 5.  8. 16.]
 [10.  4.  6.]]
