# Class Exercise: Array Generation and Manipulation

In this exercise, you will practice creating and manipulating NumPy arrays. Follow the step-by-step instructions below to complete the tasks.

## Important Notes from Chapter 3.3.2

- **Next Week's Objective:** You should be able to generate test data to study various aspects of machine learning algorithms more closely.
- **Key Functions to Learn:** `np.ones`, `np.zeros`, `np.random.rand`, `np.random.randint`, `np.random.randn`, `np.array`
  - `np.random.choice` is similar to the above functions.
- **Additional Functions:** `np.arange` and `np.linspace` perform similar tasks.
- **Other Concepts:** Slicing, `np.reshape`, and the difference between `size` and `shape`.

### Less Important Topics in Chapter 3.3.2

- **`ix_`:** Can be omitted.
- **`flatnonzero`:** You should only be able to roughly categorize it.
  - *(See Jupyter Notebook on "Selecting Elements")*

## Task a: Creating Arrays

Read Frochte Chapter 3.3.2 (p.54) and perform the following tasks in parallel.

### a.1 Create an array with 3 rows and 4 columns filled with ones.

In [6]:
import numpy as np
import pandas as pd

# Create an array with 3 rows and 4 columns filled with ones
array_ones = np.ones((3, 4))
print("Array filled with ones:")
print(array_ones)

Array filled with ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### a.2 Create an array with 2 rows and 4 columns filled with zeros.

In [7]:
# Create an array with 2 rows and 4 columns filled with zeros
array_zeros = np.zeros((2, 4))
print("Array filled with zeros:")
print(array_zeros)

Array filled with zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### a.3 Create an array with 20 rows and 2 columns filled with random numbers.

In [8]:
# Create an array with 20 rows and 2 columns filled with random numbers
array_random = np.random.rand(20, 2)
print("Array filled with random numbers:")
print(array_random)

Array filled with random numbers:
[[6.69979899e-01 6.59061284e-02]
 [7.26210894e-01 4.40606613e-01]
 [4.78069980e-01 3.64052842e-01]
 [8.35148184e-01 4.51215437e-01]
 [9.32095038e-01 5.75894036e-01]
 [6.69949312e-01 2.33868052e-01]
 [5.37955752e-01 1.40102568e-01]
 [1.17638593e-02 1.53408930e-01]
 [4.56423766e-02 9.39318823e-01]
 [9.76252187e-01 7.33812072e-01]
 [8.25089763e-01 6.92600797e-01]
 [8.89270896e-02 6.39102894e-01]
 [6.18354418e-01 9.81052216e-01]
 [1.08722748e-01 1.31387783e-01]
 [9.39742252e-01 1.48424121e-01]
 [4.78257462e-02 3.69623943e-01]
 [8.80165145e-01 3.47500478e-01]
 [3.36897745e-01 8.19661978e-01]
 [2.22954542e-01 3.31289866e-04]
 [8.97151645e-01 1.43077121e-01]]


### a.4 Create an array with 20 rows and 2 columns with uniformly distributed random numbers between 0 and 10.

In [9]:
# Create an array with uniformly distributed random numbers between 0 and 10
array_uniform = np.random.uniform(0, 10, (20, 2))
print("Array with uniformly distributed random numbers between 0 and 10:")
print(array_uniform)

Array with uniformly distributed random numbers between 0 and 10:
[[4.35578928 4.03400373]
 [0.62204983 7.80294534]
 [4.39728817 7.00005107]
 [1.66123019 1.62739573]
 [5.9500924  9.10168236]
 [6.60299594 7.31278029]
 [6.02262434 0.82537212]
 [0.42696616 6.66623124]
 [9.09414245 1.1234418 ]
 [2.33221871 0.17584002]
 [8.73205688 7.47687725]
 [3.63563194 4.82680384]
 [9.829561   9.99903206]
 [2.36090786 7.01627271]
 [0.29594921 0.98188147]
 [1.61766229 7.95636148]
 [9.80785522 7.35173587]
 [8.90900256 8.29386927]
 [7.23148609 3.76497794]
 [6.64863406 5.64903208]]


### a.5 Create an array with 20 rows and 2 columns with normally distributed random numbers, almost always above 1.

In [10]:
# Create an array with normally distributed random numbers (mean=2, std=0.5)
array_normal = np.random.normal(2, 0.5, (20, 2))
print("Array with normally distributed random numbers (mean=2, std=0.5):")
print(array_normal)

Array with normally distributed random numbers (mean=2, std=0.5):
[[2.16198257 2.32589421]
 [1.42217175 1.45465789]
 [1.2441399  1.2259381 ]
 [2.17293218 1.51882222]
 [1.87010337 2.5818839 ]
 [1.85312096 1.60335204]
 [3.19083442 2.72157666]
 [1.45481963 1.18835434]
 [2.4447518  2.80902657]
 [2.43647346 1.66448417]
 [1.06013725 2.54682896]
 [2.17303518 1.36902854]
 [2.3385279  2.16066394]
 [1.11394803 2.33992263]
 [2.51657289 1.65728441]
 [1.42474843 1.8052829 ]
 [2.03311003 1.43619883]
 [1.51108461 2.03969076]
 [1.11274915 1.17772738]
 [2.51935348 1.49988854]]


## Task b: Memorize Random Functions

Memorize the input parameters and output structure of the following NumPy random functions. Create a table as a memory aid.

### b.1 Input Parameters and Output Structure

| Function           | Input Parameters                          | Output Structure                                                                             |
|--------------------|-------------------------------------------|----------------------------------------------------------------------------------------------|
| `np.random.rand`   | `d0, d1, ..., dn` (dimensions)            | Array of shape `(d0, d1, ..., dn)` with uniform distribution over [0, 1).                  |
| `np.random.randn`  | `d0, d1, ..., dn` (dimensions)            | Array of shape `(d0, d1, ..., dn)` with standard normal distribution.                        |
| `np.random.randint`| `low, high=None, size=None, dtype=int`  | Integers from `low` (inclusive) to `high` (exclusive) if `high` is provided; otherwise from 0 to `low`.
| `np.random_sample`| `size=None`                              | Array of given shape with floats in the half-open interval [0.0, 1.0).                         |

## Task c: Working with `np.linspace` and `np.arange`

Read Frochte Chapter 3.3.2 (pp.54-55) and perform the following tasks.

### c.1 Documentation Review

Review the documentation for `numpy.linspace` and `numpy.arange`. Create a table of input and output parameters as a memory aid.

### c.2 Create and Reshape Array `a1`

1. **Create the array `a1`:**

In [11]:
a1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


2. **Reshape `a1` into a 4x3 matrix:**

In [12]:
matrix_4x3 = a1.reshape((4, 3))
print("4x3 Matrix:")
print(matrix_4x3)

4x3 Matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


3. **Reshape `a1` into a 2x6 matrix:**

In [13]:
matrix_2x6 = a1.reshape((2, 6))
print("2x6 Matrix:")
print(matrix_2x6)

2x6 Matrix:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


4. **Reshape `a1` into a 3x4 matrix:**

In [14]:
matrix_3x4 = a1.reshape((3, 4))
print("3x4 Matrix:")
print(matrix_3x4)

3x4 Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


5. **Attempt to reshape `a1` into a 3x5 matrix and observe what happens:**

In [15]:
try:
    matrix_3x5 = a1.reshape((3, 5))
    print("3x5 Matrix:")
    print(matrix_3x5)
except ValueError as e:
    print("Error:", e)

Error: cannot reshape array of size 12 into shape (3,5)


*What happens?* The reshape operation will fail because the total number of elements (12) does not match the desired shape (15).

## Task d: Advanced - Using `np.logspace`

### d.1 Create `a2` with 6 numbers from 10 to 1,000,000 with increasing intervals.

In [16]:
# Create an array with 6 numbers from 10 to 1,000,000 using logspace
a2_logspace_6 = np.logspace(1, 6, num=6, base=10)
print("Array a2 with 6 numbers from 10 to 1,000,000:")
print(a2_logspace_6)

Array a2 with 6 numbers from 10 to 1,000,000:
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06]


### d.2 Create `a2` with 9 numbers from 10 to 1,000 with increasing intervals.

In [17]:
# Create an array with 9 numbers from 10 to 1,000 using logspace
a2_logspace_9 = np.logspace(1, 3, num=9, base=10)
print("Array a2 with 9 numbers from 10 to 1,000:")
print(a2_logspace_9)

Array a2 with 9 numbers from 10 to 1,000:
[  10.           17.7827941    31.6227766    56.23413252  100.
  177.827941    316.22776602  562.34132519 1000.        ]


## Summary

- **Task a:** Practiced creating arrays with specific shapes and filled with ones, zeros, and random numbers.
- **Task b:** Memorized key NumPy random functions and their parameters.
- **Task c:** Explored `np.linspace` and `np.arange`, and practiced reshaping arrays.
- **Task d:** Learned to use `np.logspace` for generating arrays with logarithmically spaced numbers.