## Shape und Indizes

### Zugriff auf Datenstrukturen

###### Erinnerung an die Shape

In [1]:
import numpy as np

In [2]:
######### Shape
X=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print("X\n",X)
print(X.shape)
print(X.shape[0])


X
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
5


###### Erinnerung: Zugriffsmethoden bei Arrays

In [3]:
V=np.arange(10,20)
V

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
print(V[0])
print(V[0:3])
print(V[[0,1,2]])
print(V)

10
[10 11 12]
[10 11 12]
[10 11 12 13 14 15 16 17 18 19]


In [5]:
#Exkurs
#bei mehrdimensionalen Strukturen 
# bezieht sich die Liste auf die Zeilenwird vorher vektorisiert.

print("Inhalte von X\n",X)
liste=[0,1]
print("Liste",liste)
print("X wurde gefiltert\n",X[liste])


Inhalte von X
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Liste [0, 1]
X wurde gefiltert
 [[1 2]
 [3 4]]


### Wie kann man aus vielen Zeilen einige auswählen?

#### np.choice

In [6]:
zeilennummern=[0,1,2,3,4]
print("Zeilennummern",zeilennummern)
auswahl=np.random.choice(zeilennummern,3, replace=False)
print("auswahl",auswahl)

Zeilennummern [0, 1, 2, 3, 4]
auswahl [1 3 2]


In [7]:
#choice mit Konstanten
zeilennummern=[0,1,2,3,4]
print("Zeilennummern",zeilennummern)
#auswahl=np.random.choice(zeilennummern,3., replace=False)
# 2.Parameter darf nicht float sein
#korrekt ist:
auswahl=\
np.random.choice(zeilennummern,int(3.), replace=False)
print(auswahl)

Zeilennummern [0, 1, 2, 3, 4]
[3 1 0]


In [8]:
#choice mit shapes
#zeilennummern=np.arange(X.shape[0])
print("Zeilennummern",zeilennummern)
auswahl=np.random.choice(X.shape[0],3, replace=False)
print("auswahl",auswahl)

Zeilennummern [0, 1, 2, 3, 4]
auswahl [2 1 3]


In [9]:
#Anwendungsbeispiel
#trainings_indizes=np.random.choice(6,3,replace=False)
trainings_indizes=np.random.choice(X.shape[0],int(0.8*X.shape[0]),replace =False)
print("Trainingsindizes",trainings_indizes)
Xtrain=X[trainings_indizes]
print("Trainingsmenge\n",Xtrain)

Trainingsindizes [2 4 0 3]
Trainingsmenge
 [[ 5  6]
 [ 9 10]
 [ 1  2]
 [ 7  8]]


#### np.delete

In [10]:
V=np.array([10,11,12,13,14,15,16,17,18,19])
indexliste=[0,2,4]
print("behalten\n",V[indexliste])
print("löschen\n",np.delete(V,indexliste))
#Ausgangsvektor ist V, der enthält die relevanten Einträge
#indexliste bezeichnet die Indizes (Positionen) von den Elementen, die in V gelöscht werden

behalten
 [10 12 14]
löschen
 [11 13 15 16 17 18 19]


In [11]:
print("V",V)
print("Indexliste",liste)
print("anhand der Indizes einen Teil von V behalten\t",V[liste])
print("anhand der Indizes einen Teil von V löschen\t",np.delete(V,liste))

V [10 11 12 13 14 15 16 17 18 19]
Indexliste [0, 1]
anhand der Indizes einen Teil von V behalten	 [10 11]
anhand der Indizes einen Teil von V löschen	 [12 13 14 15 16 17 18 19]


## Gefäße aufbauen

In [12]:
X

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
####Arrays aufbauen
#dies nimmt man, 
#wenn man einen Array komplett aufbauen will
XX1=np.zeros((12,5))
print("Array mit 60 Nullen\n",XX1)

# Dies nimmt man, wenn man einen Array aufbauen will,
# der genauso groß, wie ein schon bekannter Array ist.
XX2=np.zeros((X.shape[0],X.shape[1]))
XX2=np.zeros(X.shape)
XX2=np.zeros_like(X)
print("neuer Array, genauso groß wie X\n",XX2)

# und jetzt kann man die Matrix verändern
XX2[2,1] =99
print("XX2 verändert\n",XX2)

Array mit 60 Nullen
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
neuer Array, genauso groß wie X
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
XX2 verändert
 [[ 0  0]
 [ 0  0]
 [ 0 99]
 [ 0  0]
 [ 0  0]]


##############################
## logische Funktionen

### np.logical_and, np.logical_not , np.logical_or

In [14]:
import numpy as np
V1=np.array([0.,0.,1.,1.,1])
V2=np.array([0.,1.,1.,1.,0.])
V3=np.logical_and(V1,V2)
#Logische Funktionen arbeiten auch auf einer Reihe von Einsen und Nullen
#Sie geben dann einen Vektor mit True und False zurück
print(V3)
print(np.logical_not(V3))


[False False  True  True False]
[ True  True False False  True]


In [15]:
import numpy as np
V1=np.array([0.,0.,1.,1.,1])
V2=np.array([0.,1.,1.,1.,0.])
V4=np.logical_or(V1,V2)
#Logische Funktionen arbeiten auch auf einer Reihe von Einsen und Nullen
#Sie geben dann einen Vektor mit True und False zurück
print(V4)
np.logical_not(V4)

[False  True  True  True  True]


array([ True, False, False, False, False])

### Einsen und Nullen zählen

In [16]:
print("Array",V3)
anzahl_einsen=np.sum(V3)
#Arithmetische Funktionen arbeiten auch auf einer Reihe von True und False
#Sie geben dann eine Zahl zurück
print("Anzahl der True",anzahl_einsen)
anzahl_nullen=V3.shape[0]- anzahl_einsen
print("Anzahl der False",anzahl_nullen)
zahl3=np.logical_not(V3).sum()
print("Anzahl der False",zahl3)


Array [False False  True  True False]
Anzahl der True 2
Anzahl der False 3
Anzahl der False 3


In [17]:
#als Alternative eventuell


np.bincount([1,1,1,2,2,10])

array([0, 3, 2, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [18]:
#als Alternative auch möglich
np.count_nonzero([1,1,1,2,2,10,0,0])

6

In [19]:
# Dieses nicht lesen, es ist vielleicht unverständlich
import numpy as np
X2=np.array([[0,0],
             [0.,1],
             [1.,1],
             [1,0]])
y=np.array([0.
            ,1.,
            1.,
            0.])
print (np.c_[X2,y])

k=1 #Spalte
#Zähle die Einsen in der Spalte k, wobei y =1 sein soll
print("y und Spalte k werden verbunden\n",np.logical_and(X2[:,k],y))
print("Zählen der Einsen in X in der k-ten Spalte, unter der Voraussetzung, das y=1")
print(np.sum(np.logical_and(X2[:,k],y)))
print("Zählen der Nullen in X in der k-ten Spalte, unter der Voraussetzung, das y=1")
print(np.sum(np.logical_and(np.logical_not(X2[:,k]),y)))
# prüfen, ob beide 0 sind
nicht_X2 =np.logical_not(X2[:,k])
print("nicht_X2",nicht_X2)
nicht_y =  np.logical_not(y)
print("nicht y",nicht_y)
und =np.logical_and(nicht_y, nicht_X2)
print("und",und)

[[0. 0. 0.]
 [0. 1. 1.]
 [1. 1. 1.]
 [1. 0. 0.]]
y und Spalte k werden verbunden
 [False  True  True False]
Zählen der Einsen in X in der k-ten Spalte, unter der Voraussetzung, das y=1
2
Zählen der Nullen in X in der k-ten Spalte, unter der Voraussetzung, das y=1
0
nicht_X2 [ True False False  True]
nicht y [ True False False  True]
und [ True False False  True]


## Häufigkeiten und bedingte Wahrscheinlichkeiten

#### bedingte Wahrscheinlichkeite ausrechnen

In [20]:
x=np.array([1,1,1,1,0,1,0,0])
y=np.array([1,1,1,1,1,0,0,0])
# hier steht original im Code X, es muss aber heißen X2D, sonst funktioniert der Code weiter unten nicht
X2D= np.array([[1],[1],[1],[0],[0],[1],[0],[0]])# X hat dieselben Inhalte wie x, aber X ist 2-dimensional
absolute_Häufigkeiten_y= np.zeros(2)
absolute_Häufigkeiten_y[0] = y.shape[0]-np.sum(y)
absolute_Häufigkeiten_y[1] = np.sum(y)
absolute_Häufigkeiten_y

array([3., 5.])

In [21]:
bedingte_Häufigkeiten_x_y=np.zeros((2,2))
bedingte_Häufigkeiten_x_y = np.array([[2,1],[1,4]])# Die werte wurden nicht mit python berechnet, sondern im Kopf
# Die erste Spalte enthält die Häufigkeiten unter der Bedingung y =0
# D.h. unter dieser Bedingung gibt es 2 Nullen in der x-Spalte und  1 Eins
# Die 2. Spalte enthält die Häufigkeiten unter der Bedingung y=1
print("bedingte_Häufigkeiten_x_y\n",bedingte_Häufigkeiten_x_y)

bedingte_Häufigkeiten_x_y
 [[2 1]
 [1 4]]


In [22]:
bedingte_Wahrscheinlichkeiten_x_y = bedingte_Häufigkeiten_x_y/absolute_Häufigkeiten_y
bedingte_Wahrscheinlichkeiten_x_y

array([[0.66666667, 0.2       ],
       [0.33333333, 0.8       ]])

#### Was tun wir, wenn eine von den x_y-Häufigkeiten = 0 ist?

In [23]:
x0=np.array([1,1,1,1,0,0,0,0])
y=np.array([1,1,1,1,1,0,0,0])
# hier steht original im Code X, es muss aber heißen X2D, sonst funktioniert der Code weiter unten nicht
X2D= np.array([[1],[1],[1],[0],[0],[1],[0],[5]])# X2D hat dieselben Inhalte wie x, aber X2D ist 2-dimensional
absolute_Häufigkeiten_y= np.zeros(2)
absolute_Häufigkeiten_y[0] = y.shape[0]-np.sum(y)
absolute_Häufigkeiten_y[1] = np.sum(y)
absolute_Häufigkeiten_y

array([3., 5.])

In [24]:
bedingte_Häufigkeiten_x0_y=np.zeros((2,2))
bedingte_Häufigkeiten_x0_y = np.array([[3,1],[0,4]])
# Die erste Spalte enthält die Häufigkeiten unter der Bedingung y =0
# D.h. unter dieser Bedingung gibt es 3 Nullen in der x-Spalte und keine 1
# Die 2. Spalte enthält die Häufigkeiten unter der Bedingung y=1
print("bedingte_Häufigkeiten_x0_y\n",bedingte_Häufigkeiten_x0_y)
bedingte_Wahrscheinlichkeiten_x0_y = bedingte_Häufigkeiten_x0_y/absolute_Häufigkeiten_y
bedingte_Wahrscheinlichkeiten_x0_y

bedingte_Häufigkeiten_x0_y
 [[3 1]
 [0 4]]


array([[1. , 0.2],
       [0. , 0.8]])

In [25]:
print("absolute_Häufigkeiten_y,  korrekt\t",absolute_Häufigkeiten_y)
absolute_Häufigkeiten_y_vermehrt = absolute_Häufigkeiten_y +1 # jeweils(!) 1 neuer Datensatz wird hinzugefügt
bedingte_Häufigkeiten_x_y_vermehrt = bedingte_Häufigkeiten_x0_y +0.5
print("absolute_Häufigkeiten_y,künstlich vermehrt  ",absolute_Häufigkeiten_y_vermehrt)
print("bedingte_Häufigkeiten_x_y,künstlich vermehrt\n",bedingte_Häufigkeiten_x_y_vermehrt)
#Mit 50% Wahrscheinlichkeit ist x =0, mir 50% Wahrscheinlichkeit ist x =1
bedingte_Wahrscheinlichkeiten_x_y_mit_smoothing = bedingte_Häufigkeiten_x_y_vermehrt/absolute_Häufigkeiten_y_vermehrt
bedingte_Wahrscheinlichkeiten_x_y_mit_smoothing

absolute_Häufigkeiten_y,  korrekt	 [3. 5.]
absolute_Häufigkeiten_y,künstlich vermehrt   [4. 6.]
bedingte_Häufigkeiten_x_y,künstlich vermehrt
 [[3.5 1.5]
 [0.5 4.5]]


array([[0.875, 0.25 ],
       [0.125, 0.75 ]])

##  Produkte aus speziellen Teilen der Matrix

### Produkte mit und ohne axis

In [26]:
print("X\n",X)
produkt=np.prod(X)
print(produkt)

X
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
3628800


In [27]:
#Erinnerung: der Parameter axis bestimmt beim Produkt, 
#ob Zeilen oder Spalten multipliziert werden.
produkt1=np.product(X,axis=1).reshape(-1,1)
print(X)
print("Produkt von allen Matrixelementen",produkt)
print("Produkt der Zeilen mit axis=1 und reshape \n",produkt1)
produkt0=np.product(X,axis=0)
#print(X)
print("Produkt der Spalten mit axis=0\n",produkt0)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Produkt von allen Matrixelementen 3628800
Produkt der Zeilen mit axis=1 und reshape 
 [[ 2]
 [12]
 [30]
 [56]
 [90]]
Produkt der Spalten mit axis=0
 [ 945 3840]


### Produkte aus ausgewählten Zellen der Matrix

In [28]:
#Erinnerung: 
#Teile aus einer Matrix ausschneiden
print(X)
print("Auschnitt\n",X[[2,0,3],[1,0,0]])
print("Produkt des Ausschnitts",np.prod(X[[2,0,3],[1,0,0]]))

#print("Liste\n",[X[0,0],X[2,1],X[1,0]])
#print("Element aus der ersten Zeilen und ersten Spalte\n",X[0][0])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Auschnitt
 [6 1 7]
Produkt des Ausschnitts 42


In [29]:
######## Produkt aus einzelnen Komponenten einer Matrix
print("X\n",X)
print("-------------------------")
produkt0=np.prod(X[[0,1,2],[1,1,1]])
print("Produkt über Indexlisten",produkt0)
produkt00 = X[0,1]*X[1,1]*X[2,1]
print("Produkt einfach über Komponenten",produkt00)

X
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
-------------------------
Produkt über Indexlisten 48
Produkt einfach über Komponenten 48


In [30]:
produkt00=X[0,0]*X[0,1]
produkt1=np.prod(X[1,[0,1]])#Indexliste in Kombination mit Einzelindex
produkt11=np.prod(X[1,0:2])#Slicing
produkt2=np.prod(X[2,[0,1]])
print("-------------------------")
print(X)
print(produkt0)
print(produkt00)
print("prod1",produkt1)
print(produkt2)
print("prod11",produkt11)

-------------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
48
2
prod1 12
30
prod11 12


## Herausnehmen des maximalen Elements aus einem Array

In [31]:
#print(V)
#V enthält Wahrsscheinlichkeiten für Kredit schlecht =0,Kredit gut=1
Wahrscheinlichkeiten=np.array([0.2,0.8])
print("Maximale Wahrscheinlichkeit",np.max(Wahrscheinlichkeiten))
print("Der wahrscheinlichste Zustand ist",np.argmax(Wahrscheinlichkeiten))
#V[9]

Maximale Wahrscheinlichkeit 0.8
Der wahrscheinlichste Zustand ist 1


In [32]:
V4=np.array([0.6,0.4])

In [ ]:
meineDiagnose=np.argmax(V4)
print("es gibt einen Kredit:",bool(meineDiagnose))

es gibt einen Kredit: False


: 